sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  global:
  - IMAGE=leaguesandbox/nexus
  - DOCKER_USERNAME=leaguesandbox
  - CLUSTER_NAME=web
  - SERVICE_ACCOUNT_NAME=nexus-deploy@league-sandbox.iam.gserviceaccount.com
  - DEPLOYMENT_NAME=Nexus
  # Docker password
  - secure: mzhtN9COt57xBvWquhT1yn7tyxIuLuEKMdKXcXvBaPFAGrhroStIC7X7loLpNAwp/36af+M3rXhl4GWXu+ET+TpbQ5A+OFEauvkbLBYlEZFQxpSVMM2fmbqFc4GR6WJusO6YXCuk0sN1aKGTFct6pihc05BtzUcWaf4hEl3EAtCIdJLdrwqK4SaA6FO8wDx119KRKvm26GZeYGRHsxB7KF9hx/Fqm6mOwkC7Z9TJjvL3xC8KUXfrPs/UEczYMN2Cyx44hbwDTb00FDIbwB1G1+lj1fBrXh8Qy6f1soSQ6taWCZ0rDo4j6rSBpCEIecE07cogOudhCeOX47Hpg1er2ZKEfQhfIEbSEBkeAyyqugHxO4KqjbzgsaBJ6+J/v+XHWbNH4f4+K/SpCRoj1CWd4vEyUy+4wbSvytWJNaAKQrBoYEApPYfMKoSGeEMn7RL1sxhCk7L0FkuaoyAWWgtl65clBW5135FiihpTucSkJnDKsQt6WHsEDKyg119SpQTNptPJB9svsjeCaJiZDm8BJGjutjNECRE/oibw8azNhaHsrfY8ZgUDfEcFMZWML8plWtpblpAl6iKBplIeRIbJaesEJO78VnSNnaKmDarSRiMMolP7FLAi8NgsFj6WEd1wvFDSouIsbyzn2XThlrhtcCJDOeRNlZ804PCrmgMkqBo=
  # Service account password
  - secure: Vwkm/yExrLwJuZCWeYWZWawXAhE0SAONhSb3QRrCCjfDOXAkmXqIIJlg4YQVIUgEAUx+vGLMnv0TqvaU41wYfHgSZ3FJxiyLFgy/efg8a87O84DM3lbE5SjQaFQiP30gAcjYERLZ4PaU3+nAy2WHGd6ZdzaA82KmUpzuiY04SECxeLqF4UMdDtQTRFvTV991UhvR5D77SeNvUBZxn0ujGrJc+7F43fEMOqCSYWeoQUaxYwDIx0TpBBrHuzn+S0KecKTrirMbuChOoAVXkiA0jVPU6iD23rVX08Nzbb3rZ73m5aOHtVIGNs3kwNbYlxwymFxSMrMWc4vkpVlTpVD2Xq8/GFUaeCne7tXtB8hs1RWYj9us4qcJrIk45lQ5v2bUq5BGHBCeOf6vmHxnsY1o6+6BgT1yVI+japv+ufcD/hkZuDbnWev9kJcXZS2JgN61ASZ1goqIAReDDEu/uuivP27SEkkhWjyZJqoC5q743LVsxjMM5rM0MJhjyUDUuypl2ZBS0RyGAm+nhF+4hTY4C3WWptkqyvflRteDX2GLdIjx82DTX6Ukdujs1B6L67/eUg+/HiFbDRKPb2lQd2wmeowPQaKFWnoaGUV6zm1YM9esHNu84zdWrl3SN6D09HXXSP7f1FV9uWaJlCkVvQhrhH41ooIaga6nihU7CeVvGTg=
  # Deploy webhook
  - secure: PlDbZYr3HW6ureVyJNGZ5ki+0endCClsL5NAfRUHnEq8gVO8n+D1b2I+yjqdci4qJtm0JILsbF0YAcA1OB0OG8GXVbnKpa2tJHx9+omhl8XbrCtnLm7cDVqMCG6X0sgb7Be88i+ZrC2uevkdLPHVN347c526gQo+YxzZ1P9EZh+xyjrbNhMUtjMzj1NlSvxGm/h7SxeIspExr/uB44+8KqAL6NRqoFYOygdv2QIMu2z4FNByQGQ86opprZoA4bANW0wWyjNTfKYZTKN7b9ZIJD9DotDXX8uyx4HY/5AQ2j7hP5j6lUQXOhwrWvsjkSHuSEeIASZ/GHbfrMtW4+gkLc33lDSISyratB7UEo6DYFbOF/SSQx1uWJaS3ewT9isbiR4XMM81xgGMFe4LuoGkcv31kCF2tyR130S6UlgJJm91nuzNMxUn/TVCLArO73LpH8502etbAtrXRXVc9VqCXYktHpUu3BxWCUdP0/gy3RMm6cBrKrcCssMV0kSEWVxrty6O5Y8al6KOcDg5gLPIIscfj7H/o2l6HzYGidMvwvIwf6SpRVDQ4lBP8hbTqtWT3Bdi8BQ7TvRaQ+7sHxAZ+/3/6v4wl8/4/x3+piKOx8S/BX2Z9fmb4pTIhBBOWBtpSU1kpFpFYm4vfPDTL4gZp2Yrruf37FQaAT8oiL/8Zwc=
jobs:
  include:
  - stage: test
    script:
    - docker build --tag $IMAGE:commit-$TRAVIS_COMMIT .
    # TODO: Implement test phase
    # - >
    #   docker run
    #   -e CI=true
    #   -e TRAVIS=true
    #   -e CODECOV_TOKEN=$CODECOV_TOKEN
    #   -e TRAVIS_BRANCH=$TRAVIS_BRANCH
    #   -e TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER
    #   -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    #   -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID
    #   -e TRAVIS_TAG=$TRAVIS_TAG
    #   -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
    #   -e TRAVIS_COMMIT=$TRAVIS_COMMIT
    #   -e DEBUG=true
    #   -e DATABASE_URL=sqlite:////tmp/app-test.db
    #   --entrypoint "/bin/sh"
    #   $IMAGE:commit-$TRAVIS_COMMIT
    #   -c "pip install -r requirements-dev.txt && pytest --cov && pip install codecov && codecov"
  - stage: build
    script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
    - docker build --tag $IMAGE:commit-$TRAVIS_COMMIT .
    - docker push $IMAGE:commit-$TRAVIS_COMMIT
  - stage: deploy
    script:
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components install kubectl
    - cd kubernetes
    - openssl aes-256-cbc -k "$SERVICE_ACCOUNT_PASSWORD" -in service-account.json.enc -out service-account.json -d
    - gcloud auth activate-service-account $SERVICE_ACCOUNT_NAME --key-file=service-account.json --project=league-sandbox
    - gcloud config set core/project league-sandbox
    - gcloud config set compute/zone europe-north1-a
    - gcloud container clusters get-credentials $CLUSTER_NAME
    - envsubst '${TRAVIS_COMMIT}' < deployment.yaml.template > deployment.yaml
    - kubectl apply -f deployment.yaml
    - sleep 10
    - kubectl exec -it $(kubectl get pod -l "app=nexus,tier=web" -o jsonpath='{.items[0].metadata.name}' --namespace nexus) --namespace nexus -- python manage.py migrate
    - "curl -H 'Content-Type: application/json' -X POST -d '{\"content\": \"'$DEPLOYMENT_NAME' updated, commit hash '$TRAVIS_COMMIT'\"}' $DEPLOY_NOTIFY_WEBHOOK"
stages:
- test
- name: build
  if: branch = master AND type = push
- name: deploy
  if: branch = master AND type = push
notifications:
  email: false
