version: '3.7'

services:

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: nexus_db
    volumes:
      - db-data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile-Nexus
    restart: always
    container_name: nexus_django
    command: /bin/bash /app/docker-entrypoint.sh
    environment:
      DATABASE_URL: psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
      SOCIAL_AUTH_GITHUB_KEY: ${SOCIAL_AUTH_GITHUB_KEY}
      SOCIAL_AUTH_GITHUB_SECRET: ${SOCIAL_AUTH_GITHUB_SECRET}
      SERVER_NAME: ${SERVER_NAME}
    depends_on:
      - db
    volumes:
      - django-data:/app/var
      - ./django:/app:ro

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-Nginx
    restart: always
    container_name: nexus_nginx
    command: /bin/bash -c "/bin/bash /root/reload.sh && nginx -g 'daemon off;'"
    environment:
      SERVER_NAME: ${SERVER_NAME}
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - django-data:/django-data:ro
      - logs:/var/log/nginx
      - certs:/etc/letsencrypt:ro
      - letsencrypt:/var/www/letsencrypt

volumes:
  db-data:
  django-data:
  logs:
  certs:
  letsencrypt:
