version: '3.7'

services:

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: /bin/bash /app/docker-entrypoint.sh
    environment:
      DATABASE_URL: psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
      SOCIAL_AUTH_GITHUB_KEY: ${SOCIAL_AUTH_GITHUB_KEY}
      SOCIAL_AUTH_GITHUB_SECRET: ${SOCIAL_AUTH_GITHUB_SECRET}
      SERVER_NAME: ${SERVER_NAME}
      PROTOCOL: ${PROTOCOL}
      GS_BUCKET_NAME: ${GS_BUCKET_NAME}
      GS_PROJECT_ID: ${GS_PROJECT_ID}
      GS_CREDENTIALS: ${GS_CREDENTIALS}
    depends_on:
      - db
    volumes:
      - django-data:/app/var
      - ./django:/app

volumes:
  db-data:
  django-data:
  caddycerts:
