version: '3.7'

services:

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: nexus_db
    volumes:
      - db-data:/var/lib/postgresql/data

  django:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app/django
