version: '3.7'

services:

  db:
    image: postgres:10.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: nexus_db
    volumes:
      - db-data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile-Nexus
    restart: always
    container_name: nexus_django
    command: /bin/bash /app/docker-entrypoint.sh
    environment:
      DATABASE_URL: psql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
      SOCIAL_AUTH_GITHUB_KEY: ${SOCIAL_AUTH_GITHUB_KEY}
      SOCIAL_AUTH_GITHUB_SECRET: ${SOCIAL_AUTH_GITHUB_SECRET}
      SERVER_NAME: ${SERVER_NAME}
    depends_on:
      - db
    volumes:
      - django-data:/app/var
      - ./django:/app:ro

  caddy:
    image: abiosoft/caddy:0.11.0-no-stats
    restart: always
    container_name: nexus_caddy
    environment:
      SERVER_NAME: ${SERVER_NAME}
      TLS_PARAMETER: ${TLS_PARAMETER}
      PROTOCOL: ${PROTOCOL}
      ACME_AGREE: "True"
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
    volumes:
      - django-data:/var/www/app:ro
      - caddycerts:/root/.caddy
      - ./caddy/Caddyfile:/etc/Caddyfile:ro

volumes:
  db-data:
  django-data:
  caddycerts:
